---
title: "RNAseq2024"
---

Date: **Date and time**

Lugar: **Centro de Investigaciones Biológicas del Noroeste, S.C.**

Instructores: [Miguel A. Tripp Valdez](https://migueltrippcv.netlify.app/), 
              [Pavel E. Galindo Torres](https://scholar.google.com/citations?hl=es&user=Cub09r0AAAAJ)

------------------------------------------------------------------------


::: {.callout-tip icon="false"}
## Objetivos del curso

- Que el alumno adquiera experiencia práctica en la utilización de herramientas  para planificar, analizar e interpretar datos de secuenciación masiva para estudios transcriptómicos (RNAseq). 
:::

#### Requisitos

-   Saber leer
-  
-   

## Temario del curso

#### MÓDULO I: Introducción a R base

1.1	Conceptos básicos (La consola en R y Rstudio, ejecutar, llamar, correr y devolver, objetos, constantes y variables, funciones, documentación, directorio de trabajo, sesión, paquetes y scripts).

1.2	Tipos de datos (Numérico, entero, carácter, factor, lógico, nulo, NA).

1.3	Operadores (Aritméticos, relacionales, lógicos y de asignación).

1.4	Estructuras de datos (Vectores, matríces, arreglos, marcos de datos, listas y coerción).

1.5	Subconjuntos (vectores, matrices y listas). 

1.6	Funciones básicas (getwd(), setwd(), length(), sort(), min(), max(), c(), seq(), t(), mean(), sd(), sum(), etc.).

1.7	Importar y exportar datos.

1.7	Instalar y cargar librerias

1.7	Creación de proyectos en Rstudio



#### MÓDULO II: Introducción a GNU/Linux
2.1	Breve historia de GNU/Linux, conociendo la terminal.

2.2	Comandos básicos.

2.3	Flujos de control básicos (if-else, for, while).

2.4	Gestionadores de paquetes.

2.5	Instalación de paquetes y manejo de ambientes conda (conda, miniconda, homebrew).

2.6	Acceso a servidores remotos.


#### Modulo IV: Análisis de datos de lecturas cortas (Illumina).
4.1	Introducción a las tecnologías de secuenciación modernas.

4.2	Control de calidad de datos (Tipos de datos, FastQC/MultiQC).

4.3	Corte de secuencias (Trimmomatic, cutadapt, fastx-toolkit).

4.4	Ensamble con genoma guiado y de novo (Trinity).

4.5	Valoración del ensamble (Transrate, BUSCO).

4.6	Análisis de genes expresados diferencialmente (Alineamiento de lecturas y estimación de la abundancia, análisis de genes y transcritos expresados diferencialmente: EdgeR, Visualización de resultados).

4.7	Anotación funcional con trinotate (BLAST, Ontología de genes, análisis de enriquecimientos funcionales (GO, KEGG), Reactome, etc.

4.8	Análisis de redes de proteínas (STRING).
